---
# tasks file for data_sciences
- name: Install pip
  apt: pkg={{ item }} state=installed
  with_items:
    - python-dev
    - python-pip
    - libblas-dev 
    - liblapack-dev 
    - libatlas-base-dev 
    - gfortran
    - build-essential

- name: Install virtualenv
  pip: name=virtualenv

- name: check if virtualenv already exists
  stat: path={{ virtualenv_dir }}
  register: venv_dir

- name: create virtualenv for dato if not exists
  shell: virtualenv {{ virtualenv_dir }}
  when: venv_dir.stat.isdir is not defined

- name: Install packages
  pip: name={{ item }} virtualenv={{ virtualenv_dir }}
  with_items:
    - jupyter
    - pandas
    - scipy
    - sklearn