---
# - hosts: mesos-master, mesos-slave
#   become: yes
#   become_method: sudo
#   roles:
#     - malk.ansible-java8-oracle

- hosts: localhost
  gather_facts: no
  vars:
    service_account_email: hoangphan@spring-paratext-112704.iam.gserviceaccount.com
    pem_file: /home/hoangphan/Downloads/hoangphan.json
    project_id: spring-paratext-112704
  tasks:
    - local_action:
        module: gce_net
        name: zookeeper-master
        allowed: tcp:2181
        fwname: zookeeper-port
