---
- name: modify host file add master node
  lineinfile: dest=/etc/hosts line="{{ item }}  spark_master"
  with_items: "{{ groups.spark_master }}"

- name: modify host file add slave node
  lineinfile: dest=/etc/hosts line="{{ item[1] }}  spark_slave_{{ item[0] }}"
  with_indexed_items: "{{ groups.spark_slave }}"

- name: Download Spark pre-built package
  get_url: url={{ spark_download_url }} dest="/tmp/spark-{{ spark_version }}.tgz"
  tags:
    - install

- name: Extract Spark archive
  unarchive: copy=no src="/tmp/spark-{{ spark_version }}.tgz" dest=/opt/
  tags:
    - install

- name: Create link to Spark directory
  file: src=/opt/spark-{{ spark_version }} dest={{ spark_root }} state=link
  tags:
    - install
