---
# tasks file for neo4j
- name: add neo4j key
  apt_key: url="http://debian.neo4j.org/neotechnology.gpg.key" state=present

- name: add neo4j repository
  apt_repository: repo="deb http://debian.neo4j.org/repo stable/" update_cache=yes

- name: Install neo4j
  apt: name=neo4j update_cache=yes
