---
# tasks file for abl_wiki
- name: create /data folder
  file: path=/data state=directory mode=0777

- name: upload copus to remote host
  copy: src=wiki-sentences.txt dest=/data/wiki-sentences.txt mode=0777

- name: install build-essential
  apt: name=build-essential update_cache=yes

# - name: Download abl
#   get_url: url="http://ilk.uvt.nl/menno/files/software/abl/abl-1.2.tar.gz" mode=0777 dest="/data/abl-1.2.tar.gz"

- name: untar the file
  unarchive: src="http://ilk.uvt.nl/menno/files/software/abl/abl-1.2.tar.gz" dest=/data/ copy=no

- name: install abl tool
  command: sudo {{ item }} chdir="/data/abl-1.2"
  with_items:
    - ./configure
    - make
    - make install

# nohup abl_align -a wm -p u -i wiki-sentences.txt -o wiki-sentences.txt.aligned &